### ISSUE TITLE
css loader Error with this template and without any update

### ISSUE THREAD

**Issue by wat2012** [vuejs-templates/webpack#1029]
PS C:\Users\Jerome\codes\zju165\webapp> npm run dev

> webapp@1.0.0 dev C:\Users\Jerome\codes\zju165\webapp
> node build/dev-server.js

> Starting dev server...

 ERROR  Failed to compile with 2 errors                                                                          

 error  in ./src/App.vue

Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/w
ebpack/extract-text-webpack-plugin for the usage example
    at Object.pitch (C:\Users\Jerome\codes\zju165\webapp\node_modules\extract-text-webpack-plugin\dist\loader.js:57:11)

 @ ./src/App.vue 2:2-376
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/components/HelloWorld.vue

Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/w
ebpack/extract-text-webpack-plugin for the usage example
    at Object.pitch (C:\Users\Jerome\codes\zju165\webapp\node_modules\extract-text-webpack-plugin\dist\loader.js:57:11)

 @ ./src/components/HelloWorld.vue 2:2-391
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

> Listening at http://localhost:8080

**Comment by LinusBorg** [comment]
Looks like for some reason, you have set the environment-variable `NODE_ENV` set to `production`  or `testing` in your terminal.

**Comment by LinusBorg** [comment]
Closing for inactivity from OP.
