### ISSUE TITLE
Unexpected token import in tests (with Jest on Windows)

### ISSUE THREAD

**Issue by kemalcany** [vuejs-templates/webpack#1094]
Hi guys,

I think the 1.2.4 release has a problem with dynamic-import-node in tests.

A default out of the box project with Jest tests gives the error below (on my Windows computer)

Do you encounter any problems in osx?

```
> vw-ssr-full@1.0.0 unit C:\Users\kemal\Desktop\Kite\_Code\third-repos\vw-ssr-full
> jest --config test/unit/jest.conf.js --coverage

 FAIL  test\unit\specs\HelloWorld.spec.js
  ● Test suite failed to run

    C:\Users\kemal\Desktop\Kite\_Code\third-repos\vw-ssr-full\test\unit\setup.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import Vue from 'vue';
                                                                                             ^^^^^^

    SyntaxError: Unexpected token import

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:305:17)
          at Generator.next (<anonymous>)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        6.853s
Ran all test suites.
Running coverage on untested files...
    Failed to collect coverage from C:\Users\kemal\Desktop\Kite\_Code\third-repos\vw-ssr-full\src\App.vue
    ERROR: SyntaxError: 'import' and 'export' may only appear at the top level (10:0)
    STACK: SyntaxError: 'import' and 'export' may only appear at the top level (10:0)
    at Parser.pp$5.raise (C:\Users\kemal\Desktop\Kite\_Code\third-repos\vw-ssr-full\node_modules\babylon\lib\index.js:4454:13)
    at Parser.pp$1.parseStatement (C:\Users\kemal\Desktop\Kite\_Code\third-repos\vw-ssr-full\node_modules\babylon\lib\index.js:1877:16)
    at Parser.parseStatement (C:\Users\kemal\Desktop\Kite\_Code\third-repos\vw-ssr-full\node_modules\babylon\lib\index.js:5910:22)
    at Parser.pp$1.parseBlockBody (C:\Users\kemal\Desktop\Kite\_Code\third-repos\vw-ssr-full\node_modules\babylon\lib\index.js:2268:21)
    at Parser.pp$1.parseBlock (C:\Users\kemal\Desktop\Kite\_Code\third-repos\vw-ssr-full\node_modules\babylon\lib\index.js:2247:8)
    at Parser.pp$3.parseFunctionBody (C:\Users\kemal\Desktop\Kite\_Code\third-repos\vw-ssr-full\node_modules\babylon\lib\index.js:4235:22)
    at Parser.parseFunctionBody (C:\Users\kemal\Desktop\Kite\_Code\third-repos\vw-ssr-full\node_modules\babylon\lib\index.js:5897:20)
    at Parser.pp$1.parseFunction (C:\Users\kemal\Desktop\Kite\_Code\third-repos\vw-ssr-full\node_modules\babylon\lib\index.js:2386:8)
    at Parser.pp$3.parseFunctionExpression (C:\Users\kemal\Desktop\Kite\_Code\third-repos\vw-ssr-full\node_modules\babylon\lib\index.js:3760:17)
    at Parser.pp$3.parseExprAtom (C:\Users\kemal\Desktop\Kite\_Code\third-repos\vw-ssr-full\node_modules\babylon\lib\index.js:3722:19)
```

**Comment by LinusBorg** [comment]
that doesn't seem to be a problem with `dynamic-import` (which is concerned with `import()` functions) - it rather seems that ES6 modules weren't transformed to commonjs, which would have been the job of the `transform-es2015-modules-commonjs` plugin.

That works for me on OSX, but I'm not sure this is a windows problem - this build was tested by @Akryum on windows as well.

Could you check out what `process.env.NODE_ENV` and process.env.BABEL_ENV`are set to for you? for that, console.log them in `/test/unit/setup.js` (and comment out the import statement so that it won't interefere befor the console had a chance to log).

I would assume that your BABEL_ENV is not set correctly.

**Comment by kemalcany** [comment]
Thanks for the help Linus, so yes so the BABEL_ENV is undefined. NODE_ENV is dev. 

Setting BABEL_ENV as `test` or `production` doesn't seem to solve the issue.

The .babelrc that comes out of the box is as follows:

To me it looks like a Karma setup but at the command prompt I've chosen Jest as my test runner, could this be the problem?

```
{
  "presets": [
    ["env", {
      "modules": false
    }],
    "stage-2"
  ],
  "plugins": ["transform-runtime"],
  "env": {
    "test": {
      "presets": ["env", "stage-2"],
      "plugins": ["transform-es2015-modules-commonjs", "dynamic-import-node"]
    }
  }
}
```

**Comment by LinusBorg** [comment]
No, babelrc is fine. The problem is that NODE_ENV is 'dev'.

You see, it goes like this:

1. Jest by defaults sets `process.env.NODE_ENV` to `test`, if it's not already set(!)
2.  if BABEL_ENV is not set, babel falls back to the value of NODE_ENV, so now BABEL_ENV is also `dev`
3. but the `.babelrc` config relies on BABEL_ENV to be `test` so that the correct env configuration is  applied.

So long story short: NODE_ENV should be `test`, or BABEL_ENV should be set to `test` by you directly.

**Comment by brandonaaskov** [comment]
@LinusBorg I think this might still be an issue. I opened #1404 and it seems closely related to this.

**Comment by larsmars** [comment]
I have the same, updated #1404
