### ISSUE TITLE
弄了好久没明白这个是什么报错

### ISSUE THREAD

**Issue by xcondor** [vuejs-templates/webpack#1145]
_http_outgoing.js:497
    throw new TypeError('The header content contains invalid characters');
    ^

TypeError: The header content contains invalid characters
    at validateHeader (_http_outgoing.js:497:11)
    at ClientRequest.setHeader (_http_outgoing.js:501:3)
    at new ClientRequest (_http_client.js:192:12)
    at TunnelingAgent.request (http.js:38:10)
    at TunnelingAgent.createSocket (C:\Program Files\nodejs\node_global\node_modules\vue-cli\node_modules\_tunnel-agent@0.6.0@tunnel-agent\index.js:135:25)
    at TunnelingAgent.createSecureSocket [as createSocket] (C:\Program Files\nodejs\node_global\node_modules\vue-cli\node_modules\_tunnel-agent@0.6.0@tunnel-agent\index.js:200:41)
    at TunnelingAgent.createConnection (C:\Program Files\nodejs\node_global\node_modules\vue-cli\node_modules\_tunnel-agent@0.6.0@tunnel-agent\index.js:98:8)
    at TunnelingAgent.addRequest (C:\Program Files\nodejs\node_global\node_modules\vue-cli\node_modules\_tunnel-agent@0.6.0@tunnel-agent\index.js:92:8)
    at new ClientRequest (_http_client.js:258:16)
    at Object.request (http.js:38:10)
    at Object.request (https.js:239:15)
    at get (C:\Program Files\nodejs\node_global\node_modules\vue-cli\node_modules\_got@6.7.1@got\index.js:33:18)
    at requestAsEventEmitter (C:\Program Files\nodejs\node_global\node_modules\vue-cli\node_modules\_got@6.7.1@got\index.js:85:2)
    at asStream (C:\Program Files\nodejs\node_global\node_modules\vue-cli\node_modules\_got@6.7.1@got\index.js:153:13)
    at Function.got.stream (C:\Program Files\nodejs\node_global\node_modules\vue-cli\node_modules\_got@6.7.1@got\index.js:321:29)
    at module.exports (C:\Program Files\nodejs\node_global\node_modules\vue-cli\node_modules\_download@5.0.3@download\index.js:55:21)

**Comment by LinusBorg** [comment]
This is not a problem with this template, but with vue-cli (and possibly your connection).
