### ISSUE TITLE
Vue webpack fails: `No matching version found for require-from-string@^1.1.0`

### ISSUE THREAD

**Issue by tianhuil** [vuejs-templates/webpack#1228]
Running `vue init webpack vueapp01` results in a `package.json` that has bad dependencies:

```
No matching version found for require-from-string@^1.1.0
```

 Here's the commands to reproduce this:

```
$ vue -V
2.9.2
$ vue init webpack vueapp01

? Target directory exists. Continue? Yes
? Project name vueapp01
? Project description A Vue.js project
? Author Tianhui Michael Li <tianhuil@cs.princeton.edu>
? Vue build standalone
? Install vue-router? No
? Use ESLint to lint your code? No
? Set up unit tests No
? Setup e2e tests with Nightwatch? No
? Should we run `npm install` for you after the project has been created? (recommended) npm

   vue-cli · Generated "vueapp01".


# Installing project dependencies ...
# ========================

npm ERR! code ETARGET
npm ERR! notarget No matching version found for require-from-string@^1.1.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'cosmiconfig'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tianhui/.npm/_logs/2018-01-06T19_40_19_704Z-debug.log

# Project initialization finished!
# ========================

To get started:

  cd vueapp01
  npm run dev

Documentation can be found at https://vuejs-templates.github.io/webpack
```

Then if I go into the repo and install:
```
$ npm install --verbose
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/Cellar/node@8/8.9.4/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'install',
npm verb cli   '--verbose' ]
npm info using npm@5.6.0
npm info using node@v8.9.4
npm verb npm-session 27b85e21030f255f
npm info lifecycle vueapp01@1.0.0~preinstall: vueapp01@1.0.0
npm http fetch GET 304 https://registry.npmjs.org/babel-helper-vue-jsx-merge-props 212ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/babel-loader 214ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/babel-plugin-transform-runtime 216ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/babel-plugin-syntax-jsx 216ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/autoprefixer 222ms (from cache)
...
npm http fetch GET 304 https://registry.npmjs.org/verror 178ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/set-value 549ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/ecc-jsbn 326ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/require-from-string 29ms (from cache)
npm verb type range
npm verb stack require-from-string: No matching version found for require-from-string@^1.1.0
npm verb stack     at pickManifest (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/npm-pick-manifest/index.js:65:11)
npm verb stack     at fetchPackument.then.packument (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/manifest.js:52:18)
npm verb stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
npm verb stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
npm verb stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
npm verb stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
npm verb stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
npm verb stack     at Async._drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
npm verb stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
npm verb stack     at Immediate.Async.drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
npm verb stack     at runCallback (timers.js:789:20)
npm verb stack     at tryOnImmediate (timers.js:751:5)
npm verb stack     at processImmediate [as _immediateCallback] (timers.js:722:5)
npm verb cwd /Users/tianhui/projects/vueapp01
npm verb Darwin 17.3.0
npm verb argv "/usr/local/Cellar/node@8/8.9.4/bin/node" "/usr/local/bin/npm" "install" "--verbose"
npm verb node v8.9.4
npm verb npm  v5.6.0
npm ERR! code ETARGET
npm ERR! notarget No matching version found for require-from-string@^1.1.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'cosmiconfig'
npm ERR! notarget
npm verb exit [ 1, true ]
```

Any thoughts on what's wrong?  I'm on OSX.
- vue: 2.9.2
- npm: v5.6.0
- node v8.9.4

**Comment by NigelEarle** [comment]
https://status.npmjs.org/incidents/41zfb8qpvrdj

**Comment by LinusBorg** [comment]
Probably related to this: https://status.npmjs.org/incidents/41zfb8qpvrdj

**Comment by LinusBorg** [comment]
According to npm status, the problem was resolved. Please open a new issue if the problem persists
