### ISSUE TITLE
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm

### ISSUE THREAD

**Issue by zwl1619** [vuejs-templates/webpack#124]
使用的是nodejs 6.1，使用过程中有些问题，麻烦解答一下：
step1：
```
//这一步好像没什么问题
$ npm install -g vue-cli
C:\Users\dell\AppData\Roaming\npm\vue -> C:\Users\dell\AppData\Roaming\npm\node_modules\vue-cli\bin\vue
C:\Users\dell\AppData\Roaming\npm
`-- vue-cli@2.1.0
```
step2：
```
//这一步不会回到命令提示符，在最后一行代码后面，应该做什么呢？
$ vue init webpack my-project

? Project name (my-project)
? Project name my-project
? Project description (A Vue.js project)
? Project description A Vue.js project
? Author (kanjiushi <kanjiushi006@163.com>)
? Author kanjiushi <kanjiushi006@163.com>
? Use ESLint to lint your code? (Y/n)
? Use ESLint to lint your code? Yes
? Pick an ESLint preset (Use arrow keys)
? Pick an ESLint preset none
? Setup unit tests with Karma + Mocha? (Y/n)
? Setup unit tests with Karma + Mocha? Yes
? Setup e2e tests with Nightwatch? (Y/n)
? Setup e2e tests with Nightwatch? Yes

   vue-cli · Generated "my-project".

   To get started:

     cd my-project
     npm install
     npm run dev

   Documentation can be found at https://vuejs-templates.github.io/webpack
```
step3:
```
//因为第二步没有退回到命令提示符，所以ctrl+c退出后，执行下一条命令
$ cd my-project
```
step4：
```
//错误如下
$ npm install
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
```
step5：
```
因为step4有错误，所以没有执行step5的命令`$ npm run dev`了。
```

**Comment by yyx990803** [comment]
第三步 ctrl c 应该不影响安装。第四步只是个警告，也不影响。如果其他都正常，应该可以跑。

**Comment by zwl1619** [comment]
第四步一直都不退出，所以ctrl+c后执行第五步，结果如下：
step5：
```
$ npm run dev

> my-project@1.0.0 dev D:\wnmp\www\laravel-entrust\public\my-project
> node build/dev-server.js

module.js:440
    throw err;
    ^

Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\wnmp\www\laravel-entrust\public\my-project\build\d                      ev-server.js:2:15)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\dell\\AppData\\R                      oaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v6.1.0
npm ERR! npm  v3.7.5
npm ERR! code ELIFECYCLE
npm ERR! my-project@1.0.0 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-project@1.0.0 dev script 'node build/dev-server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the my-project package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/dev-server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs my-project
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls my-project
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to in                      stall?

npm ERR! Please include the following file with any support request:
npm ERR!     D:\wnmp\www\laravel-entrust\public\my-project\npm-debug.log
```
