### ISSUE TITLE
Impossible to use compile beceause of new tests

### ISSUE THREAD

**Issue by TheSirC** [vuejs-templates/webpack#1245]
Hello,

I am unable to compile any file based of this template because of this commit (fd65d24ad2ed5113dfb6790c600c51e6ea572cd8) : [the file](https://github.com/vuejs-templates/webpack/commit/fd65d24ad2ed5113dfb6790c600c51e6ea572cd8#diff-72db118f6887a9485d1130960ff30631R16) now throws back an error 
```
index.js:16
    ...(isTest ? scenario : undefined)
    ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/sirc/.vue-templates/webpack/meta.js:14:28)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
```
Sorry for the bug ! :disappointed:

**Comment by LinusBorg** [comment]
The template tests require node >=8.

I'll update the engines field in package.json accordingly.

**Comment by LinusBorg** [comment]
Edit: oh snap, I'm an idiot! 

that code also runs on normal template installs! 

I'll fix this in the next hours.

**Comment by LinusBorg** [comment]
Found a few minutes right now, and it's fixed!

Thanks for the report @TheSirC

**Comment by TheSirC** [comment]
You're welcome! 
You're doing a wonderful job! Thank you!

**Comment by LinusBorg** [comment]
Thanks :)
