### ISSUE TITLE
undefined:1

### ISSUE THREAD

**Issue by jagadeshanh** [vuejs-templates/webpack#1262]
I was following QuickStart guide from https://vuejs-templates.github.io/webpack/ and installed vue-cli

but when trying to `vue init webpack vuexperiment`

I am getting an error

Version: 2.9.2

```
undefined:1
{"_id":"vue-cli","_rev":"95-5d64cd05af59883b4f923b609d955f7b","name":"vue-cli","description":"A simple CLI for scaffolding Vue.js projects.","dist-tags":{"latest":"2.9.2"},"versions":{"1.0.0":{"name":"vue-cli","version":"1.0.0","description":"Opinionated CLI for starting Vue.js single page applications","preferGlobal":true,"bin":{"vue":"bin/vue"},"scripts":{"test":"mocha"},"repository":{"type":"git","url":"git+https://github.com/vuejs/vue-cli.git"},"keywords":["vue","cli","spa"],"author":{"name":"Evan You"},"license":"MIT","bugs":{"url":"https://github.com/vuejs/vue-cli/issues"},"homepage":"https://github.com/vuejs/vue-cli#readme","main":"lib/index.js","dependencies":{"chalk":"^1.1.1","commander":"^2.9.0","download-github-repo":"^0.1.3","khaos":"^0.9.3","read-metadata":"^1.0.0","request":"^2.67.0","rimraf":"^2.5.0","uid":"0.0.2"},"gitHead":"c3daf7b2f7d3e27bf5a6b31c5ff28a6f05df47b1","_id":"vue-cli@1.0.0","_shasum":"97c5d6e66ced1931d05c13fb459c5331c25b9a85","_from":".","_npmVersion":"3.3.12","_nod

SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at Request.request [as _callback] (/usr/lib/node_modules/vue-cli/lib/check-version.js:19:34)
    at Request.self.callback (/usr/lib/node_modules/vue-cli/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/lib/node_modules/vue-cli/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/vue-cli/node_modules/request/request.js:1085:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)


```

**Comment by LinusBorg** [comment]
Seems your vue-cli installation is broken.

**Comment by LinusBorg** [comment]
Not related to this template.

**Comment by jagadeshanh** [comment]
vue init works fine...

```
Usage: vue-init <template-name> [project-name]


  Options:

    -c, --clone  use git clone
    --offline    use cached template
    -h, --help   output usage information
  Examples:

    # create a new project with an official template
    $ vue init webpack my-project

    # create a new project straight from a github template
    $ vue init username/repo my-project
```

**Comment by LinusBorg** [comment]
No, the help text for vue init works fine. 

if you read the error stack trace, the error is in: 

`usr/lib/node_modules/vue-cli/lib/check-version.js:19:34`

Which runs before the template is actually downloaded and installed. 

So it's either a bug in vue-cli or a problem with your local install. 

It's not related to this template as far as I can see.
