### ISSUE TITLE
npm run e2e fails in fresh install (Windows 7)

### ISSUE THREAD

**Issue by alexcheninfo** [vuejs-templates/webpack#127]
I'm running Windows 7.

I updated `vue-cli` to the latest version then did:

1. `vue init webpack e2e`
2. `npm install`
3. `npm run e2e`

And I got this error:

```
16:53:19.874 INFO - Launching a standalone Selenium Server
Setting system property webdriver.chrome.driver to E:\alex\e2e\node_modules\chro                              medriver\lib\chromedriver\chromedriver.exe
16:53:19.921 INFO - Java: Oracle Corporation 25.66-b18
16:53:19.921 INFO - OS: Windows 7 6.1 x86
16:53:19.921 INFO - v2.53.0, with Core v2.53.0. Built from revision 35ae25b
16:53:19.952 INFO - Driver class not found: com.opera.core.systems.OperaDriver
16:53:19.952 INFO - Driver provider com.opera.core.systems.OperaDriver is not re                              gistered
16:53:19.952 INFO - Driver provider org.openqa.selenium.safari.SafariDriver regi                              stration is skipped:
registration capabilities Capabilities [{browserName=safari, version=, platform=                              MAC}] does not match the current platform VISTA
16:53:19.952 INFO - Driver class not found: org.openqa.selenium.htmlunit.HtmlUni                              tDriver
16:53:19.952 INFO - Driver provider org.openqa.selenium.htmlunit.HtmlUnitDriver                               is not registered
16:53:20.014 WARN - Failed to start: SocketListener0@0.0.0.0:4444
java.net.BindException: Selenium is already running on port 4444. Or some other                               service is.
        at org.openqa.selenium.server.SeleniumServer.start(SeleniumServer.java:5                              09)
        at org.openqa.selenium.server.SeleniumServer.boot(SeleniumServer.java:32                              1)
        at org.openqa.selenium.server.SeleniumServer.main(SeleniumServer.java:24                              0)
        at org.openqa.grid.selenium.GridLauncher$1.launch(GridLauncher.java:58)
        at org.openqa.grid.selenium.GridLauncher.main(GridLauncher.java:127)

```

What could be the reason?

**Comment by chrisvfritz** [comment]
It looks like something is already running on port 4444. You'll have to end whatever that process is first.
