### ISSUE TITLE
`npm run dev` ERROR  `Build failed with errors.`

### ISSUE THREAD

**Issue by carvalhoviniciusluiz** [vuejs-templates/webpack#1329]
Hello,
I created a cli display project, updated the dependencies below and an error similar to #586 happened

my Vue packages 
- vue@2.5.13
- vue-loader@14.2.1
- vue-template-compiler@2.5.15

```
ERROR in ./src/App.vue
Module build failed: Error: 

Vue packages version mismatch:

- vue@2.5.13
- vue-template-compiler@2.5.15

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

    at Object.<anonymous> (/home/wow/client/node_modules/vue-template-compiler/index.js:8:9)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/wow/client/node_modules/vue-loader/lib/parser.js:1:80)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
 @ ./src/main.js 4:0-26

ERROR in ./src/components/HelloWorld.vue
Module build failed: Error: 

Vue packages version mismatch:

- vue@2.5.13
- vue-template-compiler@2.5.15

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

    at Object.<anonymous> (/home/wow/client/node_modules/vue-template-compiler/index.js:8:9)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/wow/client/node_modules/vue-loader/lib/parser.js:1:80)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
 @ ./src/router/index.js 3:0-50
 @ ./src/main.js

  Build failed with errors.
```
there were no other modifications in the project! many others had the same problem of versions.
https://stackoverflow.com/questions/43397688/how-do-i-fix-a-vue-packages-version-mismatch-error-on-laravel-spark-v4-0-9

What is the correct sequence for packet compatibility?

**Comment by carvalhoviniciusluiz** [comment]
I removed the * -lock.json files and it worked, sorry the post

**Comment by FreemenL** [comment]
https://github.com/FreemenL/empty-webpack-build-detail-plugin一个不错的插件 实时定位错误信息

**Comment by FreemenL** [comment]
https://github.com/FreemenL/empty-webpack-build-detail-plugin
