### ISSUE TITLE
SyntaxError: Unexpected token < when trying to test using jest

### ISSUE THREAD

**Issue by lben** [vuejs-templates/webpack#1335]
Hi, I have tried several solutions I have found but any of those work. I am using the webpack template with the default jest.conf.js but I am unable to test my component using webstorm.

This is my test:
```
import { shallow } from '@vue/test-utils'
import InicioSesion from '../../../src/components/InicioSesion.vue'

describe('InicioSesion.vue', () => {
  it('intenta navegar hacia Autorizacion con datos de solicitud completos',
    () => {
      const wrapper = shallow(InicioSesion)
      wrapper.setData({usuario: 'BA01001208', contraseña: '1234'})
      const button = wrapper.find('ion-button')
      button.trigger('click')
      expect(wrapper.vm.notification_data).toBe(null)
    })
})
```

this is my jest.conf.js (default)
```
const path = require('path')

module.exports = {
  rootDir: path.resolve(__dirname, '../../'),
  moduleFileExtensions: [
    'js',
    'json',
    'vue'
  ],
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1'
  },
  transform: {
    '^.+\\.js$': '<rootDir>/node_modules/babel-jest',
    '.*\\.(vue)$': '<rootDir>/node_modules/vue-jest'
  },
  snapshotSerializers: ['<rootDir>/node_modules/jest-serializer-vue'],
  setupFiles: ['<rootDir>/test/unit/setup'],
  mapCoverage: true,
  coverageDirectory: '<rootDir>/test/unit/coverage',
  collectCoverageFrom: [
    'src/**/*.{js,vue}',
    '!src/main.js',
    '!src/router/index.js',
    '!**/node_modules/**'
  ]
}
```

this is my component:

```
<template>
  <ion-content text-center>
    <ion-grid>
      <ion-row>
        <ion-col>
          <ion-label><b>Buzón de autorizaciones</b></ion-label>
        </ion-col>
      </ion-row>
      <ion-row>
        <ion-col>
          <input placeholder="Usuario"
                 v-model="usuario"
                 clearInput>
        </ion-col>
      </ion-row>
      <ion-row>
        <ion-col>
          <input type="password"
                 placeholder="Contraseña"
                 v-model="contraseña"
                 clearInput>
        </ion-col>
      </ion-row>
      <ion-row>
        <ion-col>
          <ion-button @click="ingresar">Ingresar</ion-button>
        </ion-col>
      </ion-row>
    </ion-grid>
  </ion-content>
</template>

<script>
import axios from 'axios'
import { mapGetters } from 'vuex'
import utils from '../utils'

export default {
  name: 'inicio-sesion',
  data: function () {
    return {
      usuario: '',
      contraseña: ''
    }
  },
  computed: {
    ...mapGetters([
      'ip_terminal',
      'sesión',
      'endpoint_canal',
      'mensaje_éxito_trama',
      'trama_SIG_010000',
      'trama_LV_010003',
      'trama_CON_002008',
      'notification_data'
    ])
  },
  watch: {
    notification_data: function (newVal) {
      if (newVal !== null) {
        console.debug('llamando a gestionPush desde el watch con false')
        this.gestiónPush(false)
      }
    }
  },
  methods: {
    ingresar: function () {
      ....
    },
    gestiónPush: function (logueado) {
      ....
    }
  }
}
</script>
```

and this is the error when I click in the webstorm test runner:

```
  ● Test suite failed to run

    /home/bernardo/WebstormProjects/Autorizaciones/src/components/InicioSesion.vue:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){<template>
                                                                                             ^
    
    SyntaxError: Unexpected token <

      1 | import { shallow } from '@vue/test-utils'
    > 2 | import InicioSesion from '../../../src/components/InicioSesion.vue'
      3 | 
      4 | describe('InicioSesion.vue', () => {
      5 |   it('intenta navegar hacia AutorizacionAperturaCertificadosAPlazo con datos de solicitud completos',
      
      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:316:17)
      at Object.<anonymous> (test/unit/specs/InicioSesion.spec.js:2:21)

```

how can I fix this? Thank you!

**Comment by lben** [comment]
If it helps anyone it seems that I had to do more steps detailed here:
https://vue-test-utils.vuejs.org/en/guides/testing-SFCs-with-jest.html

Now I am able to run the test of the HelloWorld.vue component without problems, nevertheless I am still facing issues on my component due to vuex. I am researching more about it

**Comment by eddyerburgh** [comment]
@lben what were the steps you had to follow? We should add any missing config to this template

**Comment by lben** [comment]
Ok, from the [link](https://vue-test-utils.vuejs.org/en/guides/testing-SFCs-with-jest.html) I posted I ran all sections except the coverage one at the end of the page.
On the Configuring Babel for Jest I didn't replace the default .babelrc content because it started to give me errors (another unexpected token with the spread operator ...mapGetters)

But I am still stuck with vuex testing (EDIT: It seems that I solved the issue, I detailed it in the next comments). I created a dummy component and a dummy test to simplify things but I am not able to get values from vuex, if you have any idea of where could be the problem that would be great.

My dummy component is:
```
<template>
    <div v-if="mostrar">
      <p>ip: {{ ip_terminal }}</p>
      <p>{{ usuario }}</p>
      <p>{{ mi_dato }}</p>
    </div>
</template>

<script>
import { mapGetters } from 'vuex'

export default {
  name: 'prueba-jest',
  data: function () {
    return {
      mostrar: true,
      mi_dato: 'Prueba Jest'
    }
  },
  computed: {
    ...mapGetters([
      'ip_terminal',
      'usuario'
    ])
  }
}
</script>

```
and my dummy test is:
```
import { shallow, createLocalVue } from '@vue/test-utils'
import vuex from 'vuex'
import PruebaJest from '@/components/PruebaJest.vue'

const localVue = createLocalVue()
localVue.use(vuex)

describe('PruebaJest.vue', () => {
  let getters
  let store

  beforeEach(() => {
    getters = {
      ip_terminal: () => '10.1.1.68',
      usuario: () => 'eddy'
    }
  })

  store = new vuex.Store({
    getters
  })

  it('verifies that I can use jest for testing', () => {
    const wrapper = shallow(PruebaJest, { store, localVue })
    expect(wrapper.html()).toContain('<p>ip: 10.1.1.68</p>')
    wrapper.vm.mostrar = false
    expect(wrapper.html()).not.toContain('<p>ip: 10.1.1.68</p>')
  })
})

```
but I am getting the following error:
```
Error: expect(string).toContain(value)

Expected string:
  "<div><p>ip: </p> <p></p> <p>Prueba Jest</p></div>"
To contain value:
  "<p>ip: 10.1.1.68</p>"
    at Object.<anonymous> (/home/bernardo/WebstormProjects/Autorizaciones/test/unit/specs/PruebaJest.spec.js:25:28)
    at Object.asyncFn (/home/bernardo/WebstormProjects/Autorizaciones/node_modules/jest-jasmine2/build/jasmine_async.js:82:37)
    at resolve (/home/bernardo/WebstormProjects/Autorizaciones/node_modules/jest-jasmine2/build/queue_runner.js:52:12)
    at new Promise (<anonymous>)
    at mapper (/home/bernardo/WebstormProjects/Autorizaciones/node_modules/jest-jasmine2/build/queue_runner.js:39:19)
    at promise.then (/home/bernardo/WebstormProjects/Autorizaciones/node_modules/jest-jasmine2/build/queue_runner.js:73:82)
    at <anonymous>

```
As you can see my shallow wrapper does not render the vuex getters on the template, do you have any idea where am I doing things wrong? Thank you!

**Comment by lben** [comment]
Updating this issue I had to initialize the store inside the beforeEach in order to access the getters:
```
beforeEach(() => {
    getters = {
      ip_terminal: () => '10.1.1.68',
      usuario: () => 'eddy'
    }
    store = new vuex.Store({
      getters
    })
  })
```
Now the first expect passes: 
`expect(wrapper.html()).toContain('<p>ip: 10.17.13.68</p>')`
but after changing the component's data the second expect does not pass:
`expect(wrapper.html()).not.toContain('<p>ip: 10.17.13.68</p>')`

My updated test is the following:
```
import { shallow, createLocalVue } from '@vue/test-utils'
import vuex from 'vuex'
import PruebaJest from '@/components/PruebaJest.vue'

const localVue = createLocalVue()
localVue.use(vuex)

describe('PruebaJest.vue', () => {
  let getters
  let store

  beforeEach(() => {
    getters = {
      ip_terminal: () => '10.1.1.68',
      usuario: () => 'eddy'
    }
    store = new vuex.Store({
      getters
    })
  })

  it('verifies that I can use jest for testing', () => {
    const wrapper = shallow(PruebaJest, { store, localVue })
    expect(wrapper.html()).toContain('<p>ip: 10.17.13.68</p>')
    wrapper.setData({ mostrar: false })
    expect(wrapper.html()).not.toContain('<p>ip: 10.17.13.68</p>')
  })
})

```

The first time I call wrapper.html() I get the html as expected but the second time I call html() after the setData call I get undefined. Why is this? Thanks

**Comment by lben** [comment]
I am sorry to clutter this issue too much but it seems that it is working now. I got undefined because the v-if didn't rendered anything but I was expecting a comment instead of undefined but updating the component's template to:
```
<template>
  <div>
    <div v-if="mostrar">
      <p>ip: {{ ip_terminal }}</p>
      <p>{{ usuario }}</p>
      <p>{{ mi_dato }}</p>
    </div>
  </div>
</template>
```
shows that when mostrar is false wrapper.html is:
`<div><!----></div>`
so it is working fine, thank you. I think you can close this issue if you want.
