### ISSUE TITLE
Cant get bot to work?! PLS HELP

### ISSUE THREAD

**Issue by vKFORMAL** [vuejs-templates/webpack#1343]
Charless-MBP:bot GavinMcWhirter$ node .module.js:130
    throw e;    ^
SyntaxError: Error parsing /Users/GavinMcWhirter/Desktop/xcode/bot/package.json: Unexpected end of JSON
input
    at JSON.parse (<anonymous>)
    at readPackage (module.js:126:52)
    at tryPackage (module.js:136:13)
    at Function.Module._findPath (module.js:218:20)
    at Function.Module._resolveFilename (module.js:545:25)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
Charless-MBP:bot GavinMcWhirter$

**Comment by afontcu** [comment]
Hi,

It's hard to tell what's going on without seeing your `package.json` file. There's probably a syntax error. Try to [lint your JSON file here](https://jsonlint.com/).

Hope it helps!

**Comment by LinusBorg** [comment]
Please use forum.vuejs.org
