### ISSUE TITLE
Fresh Install: "extract-text-webpack-plugin" loader is used without the corresponding plugin

### ISSUE THREAD

**Issue by CiscoKidxx** [vuejs-templates/webpack#1412]
OS: WIndows 7 Pro
Node: 8.9.4
NPM: 6.1
vue-cli: 2.5.16
vue-cli-template-webpack: 1.3.1

After a fresh `vue init webpack my_project`, running  `npm run dev` produces the following errors:

I should note that `npm run build` works flawlessly.

> ERROR  Failed to compile with 2 errors                                                                                          17:00:31
> 
> 
>  error  in ./src/App.vue
> 
> Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/we
> bpack/extract-text-webpack-plugin for the usage example
>     at Object.pitch (C:\projects\drucaas.com\node_modules\extract-text-webpack-plugin\dist\loader.js:57:11)
> 
>  @ ./src/App.vue 2:2-358
>  @ ./src/main.js
>  @ multi C:/Projects/drucaas.com/node_modules/webpack-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js
> 
> 
>  error  in ./src/components/HelloWorld.vue
> 
> Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/we
> bpack/extract-text-webpack-plugin for the usage example
>     at Object.pitch (C:\projects\drucaas.com\node_modules\extract-text-webpack-plugin\dist\loader.js:57:11)
> 
>  @ ./src/components/HelloWorld.vue 2:2-373
>  @ ./src/router/index.js
>  @ ./src/main.js
>  @ multi C:/Projects/drucaas.com/node_modules/webpack-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js
`

**Comment by jlestel** [comment]
Hello did you find a way to resolve this ?
