### ISSUE TITLE
Error while npm run dev

### ISSUE THREAD

**Issue by alvinisasi** [vuejs-templates/webpack#1457]
Hello, i have a problem when i run command "npm run dev". If i run it at first time it can work, but when i stop it and run anymore it can't work again. Here are the output:

> tuku@1.0.0 dev /home/joni/tuku
> node build/dev-server.js

> Starting dev server...
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Server.setupListenHandle [as _listen2] (net.js:1360:14)
    at listenInCluster (net.js:1401:12)
    at Server.listen (net.js:1485:7)
    at Function.listen (/home/joni/tuku/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/home/joni/tuku/build/dev-server.js:86:20)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tuku@1.0.0 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tuku@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/joni/.npm/_logs/2018-10-22T13_29_28_831Z-debug.log

**Comment by litterboys** [comment]
command ctrl + c  stop the port 8080, command 'npm run dev'  again

**Comment by alvinisasi** [comment]
> command ctrl + c stop the port 8080, command 'npm run dev' again

thank you it is work
