### ISSUE TITLE
Module build failed. No ESLint configuration found.

### ISSUE THREAD

**Issue by Syler921** [vuejs-templates/webpack#1463]
I have the following issue when i try to build my vue-cli 3.0 project : 

```
Building for production...

 ERROR  Failed to compile with 1 errors                                                                                                                                                                             
Module build failed (from ./node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 0)
No ESLint configuration found.

    at Config.getLocalConfigHierarchy (C:\_APP\projects\vuePreviewProject\vue-preview\node_modules\eslint\lib\config.js:255:39)
    at Config.getConfigHierarchy (C:\_APP\projects\vuePreviewProject\vue-preview\node_modules\eslint\lib\config.js:179:43)
    at Config.getConfigVector (C:\_APP\projects\vuePreviewProject\vue-preview\node_modules\eslint\lib\config.js:286:21)
    at Config.getConfig (C:\_APP\projects\vuePreviewProject\vue-preview\node_modules\eslint\lib\config.js:329:29)
    at processText (C:\_APP\projects\vuePreviewProject\vue-preview\node_modules\eslint\lib\cli-engine.js:163:33)
    at CLIEngine.executeOnText (C:\_APP\projects\vuePreviewProject\vue-preview\node_modules\eslint\lib\cli-engine.js:620:17)
    at lint (C:\_APP\projects\vuePreviewProject\vue-preview\node_modules\eslint-loader\index.js:253:17)
    at transform (C:\_APP\projects\vuePreviewProject\vue-preview\node_modules\eslint-loader\index.js:231:18)
    at C:\_APP\projects\vuePreviewProject\vue-preview\node_modules\loader-fs-cache\index.js:127:18
    at ReadFileContext.callback (C:\_APP\projects\vuePreviewProject\vue-preview\node_modules\loader-fs-cache\index.js:31:14)

You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.
 ERROR  Build failed with errors.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! preview@0.1.0 build: `vue-cli-service build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the preview@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\stsankov\AppData\Roaming\npm-cache\_logs\2018-11-13T15_16_14_357Z-debug.log

```

Тhe problem occurs when i install one of the dependencies from my local machine ( not from github ) : 

![image](https://user-images.githubusercontent.com/23247064/48425713-0ae50480-e76e-11e8-8dc0-deae1a75de01.png)

Аnyone who has encountered the problem ? 

Thanks,

**Comment by Syler921** [comment]
Solution refference:  https://github.com/vuejs/vue-cli/issues/2948
