### ISSUE TITLE
Unhandled Promise Rejection Warning

### ISSUE THREAD

**Issue by ghost** [vuejs-templates/webpack#1492]
Hi!

When setting this project up for the first time I get warnings from node. What is the ideal node version to run with this project? It does indeed start at port 8080, but I'd like to fix whatever error is here. Not sure if this is just to ignore or to investigate, any input?

My node version is 10.0.0

```
(node:2268) UnhandledPromiseRejectionWarning: Error: Exited with code 3
    at ChildProcess.cp.once.code (/var/www/html/logima.io/pwa/logima/node_modules/opn/index.js:85:13)
    at Object.onceWrapper (events.js:275:13)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:947:16)
    at Socket.stream.socket.on (internal/child_process.js:368:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close [as _onclose] (net.js:598:12)
(node:2268) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2268) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Thanks!

**Comment by prcongithub** [comment]
Any fix for this? I am facing similar issue after adding ```babel-polyfill``` and running it inside docker.
