### ISSUE TITLE
brace-expansion module

### ISSUE THREAD

**Issue by rdpascua** [vuejs-templates/webpack#155]
Fresh installation gives me this error

```
> node build/dev-server.js

Listening at http://localhost:8080

webpack built c7fecbbc8f83a1bcf66e in 459ms
Unhandled rejection Error: Cannot find module 'brace-expansion'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/storage/projects/foo/node_modules/minimatch/minimatch.js:10:14)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/storage/projects/foo/node_modules/readdirp/readdirp.js:5:18)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)

Hash: c7fecbbc8f83a1bcf66e
```

Edit: I'm using vue-cli `2.1.0`

**Comment by XaroRSA** [comment]
+1

**Comment by chrisvfritz** [comment]
@rdpascua @XaroRSA Can both of you share your OS and node version?

**Comment by XaroRSA** [comment]
NPM 3.9.6
Windows 7 64bit

**Comment by chrisvfritz** [comment]
@XaroRSA What about the node version (`node -v`)?

**Comment by XaroRSA** [comment]
Node 4.2.2

**Comment by rdpascua** [comment]
I'm using ubuntu 14.04(x64), it was functioning before

**Comment by chrisvfritz** [comment]
I still have no idea why the `brace-expansion` module is throwing `Unhandled rejection` on some systems. It doesn't seem to be a known issue. But it wasn't too hard to just removed the dependency that relies on that module, so I'm thinking all should be well now. @XaroRSA @rdpascua Can either of you confirm the fix?

**Comment by rdpascua** [comment]
I can confirm this fixes the issue

```bash
Listening at http://localhost:8080

webpack built 1a6fc33678ed2092d85a in 2222ms
Hash: 1a6fc33678ed2092d85a
Version: webpack 1.13.1
Time: 2222ms
     Asset       Size  Chunks             Chunk Names
    app.js    1.06 MB       0  [emitted]  app
index.html  237 bytes          [emitted]  
Child html-webpack-plugin for "index.html":
         Asset     Size  Chunks       Chunk Names
    index.html  21.4 kB       0       
webpack: bundle is now VALID.

```

**Comment by chrisvfritz** [comment]
Thanks!
