### ISSUE TITLE
async/await in .vue file

### ISSUE THREAD

**Issue by funkyLover** [vuejs-templates/webpack#173]
I want to use `async/await` with vue
here is my `eslintrc`
```
module.exports = {
  root: true,
  // https://github.com/feross/standard/blob/master/RULES.md#javascript-standard-style
  extends: 'standard',
  parser: "babel-eslint",
  parserOptions: {
    sourceType: 'module'
  },
  // required to lint *.vue files
  plugins: [
    'html'
  ],
  // add your custom rules here
  'rules': {
    // allow paren-less arrow functions
    'arrow-parens': 0,
    // allow debugger during development
    'no-debugger': process.env.NODE_ENV === 'production' ? 2 : 0
  }
}
```

and `.babelrc`
```
{
  "presets": ["es2015", "stage-0", "async-to-bluebird"],
  "plugins": ["transform-runtime"],
  "comments": false
}
```

but I get an error when `npm run dev`
```
ERROR in ./src/App.vue
Module build failed: TypeError: Cannot read property 'value' of undefined
    at getStarToken (/Users/funkyLover/Desktop/YOGO_Project/Front_End_Client/story0.1/node_modules/eslint/lib/rules/generator-star-spacing.js:68:25)
    at EventEmitter.checkFunction (/Users/funkyLover/Desktop/YOGO_Project/Front_End_Client/story0.1/node_modules/eslint/lib/rules/generator-star-spacing.js:123:29)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
    at NodeEventGenerator.enterNode (/Users/funkyLover/Desktop/YOGO_Project/Front_End_Client/story0.1/node_modules/eslint/lib/util/node-event-generator.js:40:22)
    at CodePathAnalyzer.enterNode (/Users/funkyLover/Desktop/YOGO_Project/Front_End_Client/story0.1/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:607:23)
    at CommentEventGenerator.enterNode (/Users/funkyLover/Desktop/YOGO_Project/Front_End_Client/story0.1/node_modules/eslint/lib/util/comment-event-generator.js:97:23)
    at Controller.traverser.traverse.enter (/Users/funkyLover/Desktop/YOGO_Project/Front_End_Client/story0.1/node_modules/eslint/lib/eslint.js:905:36)
    at Controller.__execute (/Users/funkyLover/Desktop/YOGO_Project/Front_End_Client/story0.1/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/Users/funkyLover/Desktop/YOGO_Project/Front_End_Client/story0.1/node_modules/estraverse/estraverse.js:501:28)
    at Controller.Traverser.controller.traverse (/Users/funkyLover/Desktop/YOGO_Project/Front_End_Client/story0.1/node_modules/eslint/lib/util/traverser.js:36:33)
    at EventEmitter.module.exports.api.verify (/Users/funkyLover/Desktop/YOGO_Project/Front_End_Client/story0.1/node_modules/eslint/lib/eslint.js:902:23)
    at EventEmitter.eslint.verify (/Users/funkyLover/Desktop/YOGO_Project/Front_End_Client/story0.1/node_modules/eslint-plugin-html/src/index.js:68:21)
    at /Users/funkyLover/Desktop/YOGO_Project/Front_End_Client/story0.1/node_modules/eslint/lib/cli-engine.js:244:45
    at Array.forEach (native)
    at processText (/Users/funkyLover/Desktop/YOGO_Project/Front_End_Client/story0.1/node_modules/eslint/lib/cli-engine.js:243:22)
 @ ./src/main.js 7:11-27
```

How should I config my `.eslintrc` or `.babelrc` or anything else for using `async/await`?

**Comment by chrisvfritz** [comment]
This sounds like a general Babel/ESLint question, rather than a bug / feature request with the template, which is what we try to reserve the issues for. I recommend posting something in a forum or chat dedicated to those two technologies.
