### ISSUE TITLE
npm run build的时候报错

### ISSUE THREAD

**Issue by ssapym** [vuejs-templates/webpack#20]
npm run build

> vue-test@ build /data/www/test/vue-test
> rimraf dist && webpack --progress --hide-modules --config build/webpack.prod.conf.js

/data/www/test/vue-test/build/webpack.prod.conf.js:25
config.vue.loaders = {
                   ^

TypeError: Cannot set property 'loaders' of undefined
    at Object.<anonymous> (/data/www/test/vue-test/build/webpack.prod.conf.js:25:20)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at module.exports (/data/www/test/vue-test/node_modules/webpack/bin/convert-argv.js:80:13)
    at Object.<anonymous> (/data/www/test/vue-test/node_modules/webpack/bin/webpack.js:39:40)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

**Comment by yyx990803** [comment]
https://github.com/vuejs-templates/webpack/commit/e9060388463e29bb52ba45a5dbeec830863b2e72
