### ISSUE TITLE
Completele out-of-date? .. Or?

### ISSUE THREAD

**Issue by tvld** [vuejs-templates/webpack#204]
With Ubuntu 14.04 / node v5.12 (also tried v4 & v6), running 
``vue init webpack my-app ``
``cd my-app & npm install``

gives:
```
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
```
And below the folder-tree:
```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
```
And when trying to run:
```
npm run dev

> my-app@1.0.0 dev /home/tom/Projects/QRespi/dev/my-app
> node build/dev-server.js

events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:893:11)
    at exports._exceptionWithHostPort (util.js:916:20)
    at Server.__dirname.Server.Server._listen2 (net.js:1246:14)
    at listen (net.js:1282:10)
    at Server.__dirname.Server.Server.listen (net.js:1378:5)
    at EventEmitter.listen (/home/tom/Projects/QRespi/dev/my-app/node_modules/express/lib/application.js:617:24)
    at Object.<anonymous> (/home/tom/Projects/QRespi/dev/my-app/build/dev-server.js:59:22)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
    at node.js:405:3

npm ERR! Linux 3.13.0-92-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "dev"
npm ERR! node v5.12.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! my-app@1.0.0 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the my-app@1.0.0 dev script 'node build/dev-server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the my-app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/dev-server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs my-app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls my-app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/tom/Projects/QRespi/dev/my-app/npm-debug.log
```
Should we not use this template anymore? I am a vue- newbie... missing something?

**Comment by chrisvfritz** [comment]
We do have some dependencies that we'd like to update 1-by-1 soon, but your problem is unrelated to them. The vital line is:

```
Error: listen EADDRINUSE :::8080
```

That means another application on your system is already bound to port 8080. I don't remember if this also works on Linux, but on OS X, I usually run `lsof -iTCP -sTCP:LISTEN -n -P` and it'll give you a list of all the processes bound to ports. Find the one that's bound to `8080` then `kill -9 PROCESS_PID` (replacing `PROCESS_PID` with the actual PID of the process).

**Comment by tvld** [comment]
Excellent. Thank you. All the deprecation warnings put on the wrong foot.

Indeed `` lsof -i :8080`` showed that I had syncthing-gui running on that port. Setting that one to different port and now... Vue welcomes me ;)

Thanks !
