### ISSUE TITLE
Npm install failed (Failed at the chromedriver@2.22.2 install script 'node install.js')

### ISSUE THREAD

**Issue by ghprod** [vuejs-templates/webpack#212]
Hi anyone experience this?

```
Downloading http://chromedriver.storage.googleapis.com/2.22/chromedriver_linux64.zip
Saving to /tmp/chromedriver/chromedriver_linux64.zip
Receiving...
Received 781K...
Received 1562K...
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:873:11)
    at TCP.onread (net.js:557:26)
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN optional dep failed, continuing fsevents@1.0.14

> spawn-sync@1.0.15 postinstall /home/ferri/Developments/domains/vue-bootstrap/node_modules/cross-spawn/node_modules/spawn-sync
> node postinstall


> phantomjs-prebuilt@2.1.10 install /home/ferri/Developments/domains/vue-bootstrap/node_modules/phantomjs-prebuilt
> node install.js

Considering PhantomJS found at /usr/local/bin/phantomjs
Found PhantomJS at /usr/local/bin/phantomjs ...verifying
Writing location.js file
PhantomJS is already installed on PATH at /usr/local/bin/phantomjs
npm ERR! Linux 3.19.0-65-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE

npm ERR! chromedriver@2.22.2 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the chromedriver@2.22.2 install script 'node install.js'.
npm ERR! This is most likely a problem with the chromedriver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs chromedriver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls chromedriver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ferri/Developments/domains/vue-bootstrap/npm-debug.log
```

Thanks

**Comment by ghprod** [comment]
Solution:

after upgrading npm with `npm install -g npm`, then run `npm install`, then everything is fine..
