### ISSUE TITLE
Can't change port

### ISSUE THREAD

**Issue by DenMesh** [vuejs-templates/webpack#360]
Tried to change the port dev-server runs on from 8080 to anything, no luck. I am changing the "port" property in config/index.js and I always get the same error:

> events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: listen EADDRINUSE :::8081
    at Object.exports._errnoException (util.js:874:11)
    at exports._exceptionWithHostPort (util.js:897:20)
    at Server._listen2 (net.js:1234:14)
    at listen (net.js:1270:10)
    at Server.listen (net.js:1366:5)
    at EventEmitter.listen (/home/remote/projects/domorost_partners/client/node_modules/express/lib/application.js:617:24)
    at Object.<anonymous> (/home/remote/projects/domorost_partners/client/build/dev-server.js:62:22)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3

I did check the ports I try and none of them are used, AFAIK. The issue arises due to port 8080 being already occupied and a need to configure Nginx for HMR to work. The _ONLY_ edit I made to the config was the port number.

**Comment by LinusBorg** [comment]
Well, since the error explicitly states that the port *is* already used, there's not much we can do. I can certainly not reproduce this.
