### ISSUE TITLE
Install issue, fsevents related

### ISSUE THREAD

**Issue by LauriePaulin** [vuejs-templates/webpack#383]
Hi,

Get this error when trying to run webpack Vue 2 CLI version:

```
D:\Vue\gomapdo-offer>npm run dev

> gomapdo-offer@1.0.0 dev D:\Vue\gomapdo-offer
> node build/dev-server.js

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 0.0.0.0:8080
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server._listen2 (net.js:1244:19)
    at listen (net.js:1293:10)
    at Server.listen (net.js:1389:5)
    at EventEmitter.listen (D:\Vue\gomapdo-offer\node_modules\express\lib\applic
ation.js:617:24)
    at Object.<anonymous> (D:\Vue\gomapdo-offer\build\dev-server.js:60:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Laurie\\AppData\
\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! gomapdo-offer@1.0.0 dev: `node build/dev-server.js`
npm ERR! Exit status 1
```

It would appear to be related to fsevents.  I get this message on install that fsvents not supported on this platform (WIN7):

```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\ch
okidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"
})
```

webpack-simple installs with no issues.

Any suggestions please?

**Comment by simplesmiler** [comment]
Regarding fsevents, it is unrelated.
`EACCES` means you don't have permissions to listen on the given address. I would guess it's due to firewall/antivirus settings. Try listening on a different port (e.g. `8079`) or different address (e.g. `localhost` or `127.0.0.1`).

**Comment by LauriePaulin** [comment]
That was it, thanks for helping a noob :-)
