### ISSUE TITLE
The dev script is not working with disabled linting

### ISSUE THREAD

**Issue by hettiger** [vuejs-templates/webpack#482]
This is on a clean project following the official install instructions of this repository.

```bash
$ vue init webpack my-project

  This will install Vue 2.x version of the template.

  For Vue 1.x use: vue init webpack#1.0 my-project

? Project name my-project
? Project description A Vue.js project
? Author Martin Hettiger <...>
? Vue build standalone
? Install vue-router? Yes
? Use ESLint to lint your code? No
? Setup unit tests with Karma + Mocha? No
? Setup e2e tests with Nightwatch? No

$ cd my-project
$ npm install
$ npm run dev

> my-project@1.0.0 dev /Users/martin/Desktop/my-project
> node build/dev-server.js

module.js:471
    throw err;
    ^

Error: Cannot find module 'eslint-friendly-formatter'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/martin/Desktop/my-project/build/webpack.base.conf.js:5:31)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! my-project@1.0.0 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the my-project@1.0.0 dev script 'node build/dev-server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the my-project package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/dev-server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs my-project
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls my-project
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/martin/Desktop/my-project/npm-debug.log
```

**Comment by limichange** [comment]
This is a bug. 
You can fix this by remove `var eslintFriendlyFormatter = require('eslint-friendly-formatter')` at `build/webpack.base.conf.js`.

**Comment by limichange** [comment]
The PR #483 will fix it.
:)

**Comment by hettiger** [comment]
Thank you @limichange
