### ISSUE TITLE
e2e test always times out

### ISSUE THREAD

**Issue by TheDutchCoder** [vuejs-templates/webpack#558]
Whenever I try to run my e2e on a clean install, I get timeout errors, even though the browser opens and correctly renders all elements.

```
> node test/e2e/runner.js

Starting selenium server... started - PID:  700

[Test] Test Suite
=====================

Running:  default e2e tests
(node:696) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.

Starting to optimize CSS...
> Listening at http://localhost:8080

 ✖ Timed out while waiting for element <#app> to be present for 10000 milliseconds.  - expected "visible" but got: "not found"
    at Object.defaultE2eTests [as default e2e tests] (/Users/reinierkaper/projects/tests/test/e2e/specs/test.js:13:8)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
```

Any idea why this happens?

I'm running pretty much the default test:
```
// For authoring Nightwatch tests, see
// http://nightwatchjs.org/guide#usage

module.exports = {
  'default e2e tests': function (browser) {
    // automatically uses dev Server port from /config.index.js
    // default: http://localhost:8080
    // see nightwatch.conf.js
    const devServer = browser.globals.devServerURL

    browser
      .url(devServer)
      .waitForElementVisible('#app', 10000)
      .assert.elementPresent('.ui-slider')
      .end()
  }
}
```

**Comment by TheDutchCoder** [comment]
I'm an idiot, #app gets replaced obviously.
Nothing to see here :|
