### ISSUE TITLE
test fails on unit tests

### ISSUE THREAD

**Issue by amgadserry** [vuejs-templates/webpack#581]
this is almost a fresh install i just added a couple more components but none related to testing when i tried npm run unit i get this 

```
 npm run unit

> revo@1.0.0 unit xxxx/x/xxxxxx
> cross-env BABEL_ENV=test karma start test/unit/karma.conf.js --single-run

07 03 2017 10:37:33.023:ERROR [plugin]: Error during loading "xxxx/x/xxxxxx/node_modules/karma-phantomjs-launcher" plugin:
  Path must be a string. Received null
07 03 2017 10:37:36.993:INFO [karma]: Karma v1.5.0 server started at http://0.0.0.0:9876/
07 03 2017 10:37:36.993:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
07 03 2017 10:37:36.994:ERROR [karma]: Found 1 load error

npm ERR! Linux 4.4.0-64-generic
npm ERR! argv "xxxx/x/xxxxxx/.nvm/versions/node/v7.7.0/bin/node" "/home/amgadserry/.nvm/versions/node/v7.7.0/bin/npm" "run" "unit"
npm ERR! node v7.7.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! revo@1.0.0 unit: `cross-env BABEL_ENV=test karma start test/unit/karma.conf.js --single-run`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the revo@1.0.0 unit script 'cross-env BABEL_ENV=test karma start test/unit/karma.conf.js --single-run'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the revo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env BABEL_ENV=test karma start test/unit/karma.conf.js --single-run
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs revo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls revo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!    xxxx/x/xxxxxx/npm-debug.log

```

here is the log file 
```

0 info it worked if it ends with ok
1 verbose cli [ 'xxxx/x/xxxxxx/.nvm/versions/node/v7.7.0/bin/node',
1 verbose cli   'xxxx/x/xxxxxx/.nvm/versions/node/v7.7.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'unit' ]
2 info using npm@4.1.2
3 info using node@v7.7.0
4 verbose run-script [ 'preunit', 'unit', 'postunit' ]
5 info lifecycle revo@1.0.0~preunit: revo@1.0.0
6 silly lifecycle revo@1.0.0~preunit: no script for preunit, continuing
7 info lifecycle revo@1.0.0~unit: revo@1.0.0
8 verbose lifecycle revo@1.0.0~unit: unsafe-perm in lifecycle true
9 verbose lifecycle revo@1.0.0~unit: PATH: xxxx/x/xxxxxx/.nvm/versions/node/v7.7.0/lib/node_modules/npm/bin/node-gyp-bin:xxxx/x/xxxxxx/node_modules/.bin:xxxx/x/xxxxxx/.nvm/versions/node/v7.7.0/bin:xxxx/x/xxxxxx/bin:xxxx/x/xxxxxx/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
10 verbose lifecycle revo@1.0.0~unit: CWD: xxxx/x/xxxxxx
11 silly lifecycle revo@1.0.0~unit: Args: [ '-c',
11 silly lifecycle   'cross-env BABEL_ENV=test karma start test/unit/karma.conf.js --single-run' ]
12 silly lifecycle revo@1.0.0~unit: Returned: code: 1  signal: null
13 info lifecycle revo@1.0.0~unit: Failed to exec unit script
14 verbose stack Error: revo@1.0.0 unit: `cross-env BABEL_ENV=test karma start test/unit/karma.conf.js --single-run`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (xxxx/x/xxxxxx/.nvm/versions/node/v7.7.0/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (xxxx/x/xxxxxx/.nvm/versions/node/v7.7.0/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid revo@1.0.0
16 verbose cwd xxxx/x/xxxxxx
17 error Linux 4.4.0-64-generic
18 error argv "xxxx/x/xxxxxx/.nvm/versions/node/v7.7.0/bin/node" "xxxx/x/xxxxxx/.nvm/versions/node/v7.7.0/bin/npm" "run" "unit"
19 error node v7.7.0
20 error npm  v4.1.2
21 error code ELIFECYCLE
22 error revo@1.0.0 unit: `cross-env BABEL_ENV=test karma start test/unit/karma.conf.js --single-run`
22 error Exit status 1
23 error Failed at the revo@1.0.0 unit script 'cross-env BABEL_ENV=test karma start test/unit/karma.conf.js --single-run'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the revo package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     cross-env BABEL_ENV=test karma start test/unit/karma.conf.js --single-run
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs revo
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls revo
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by amgadserry** [comment]
fixed with node ./node_modules/phantomjs-prebuilt/install.js
