### ISSUE TITLE
There was an error while starting the Selenium server

### ISSUE THREAD

**Issue by charliekassel** [vuejs-templates/webpack#640]
Not sure if this is my java version? `build 1.8.0_121-b13`

Step to reproduce:

```bash
vue init webpack vue-test
cd vue-test
npm install
npm test
```

Produces:
```
> node test/e2e/runner.js

> Starting dev server...

Starting to optimize CSS...
> Listening at http://localhost:8080

Starting selenium server... There was an error while starting the Selenium server:

Exception in thread "main" java.lang.UnsupportedClassVersionError: org/openqa/grid/selenium/GridLauncherV3 : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)


npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "e2e"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-test@1.0.0 e2e: `node test/e2e/runner.js`
npm ERR! Exit status 1
...
```

**Comment by LinusBorg** [comment]
From what I found through googling this error message, this seems indeed to be connected to the Java version.

**Comment by LinusBorg** [comment]
Closing this as I don't think we can do anything about this.

**Comment by liuchunhui** [comment]
why?

**Comment by charliekassel** [comment]
Can you recommend a specific java version or range to use?

**Comment by aaronxie7** [comment]
I have the same problem，and i reinstall java to the latest version, then the error disappear.

**Comment by allgood2386** [comment]
I've run straight into this problem and am left guessing which version of java I need for my dockerfile here. I second the suggestion to document this and have a recommended version.

**Comment by allgood2386** [comment]
For what it's worth the following worked for me, seems attached to java 9 which is not installed in the default node image. If you are not using alpine this should work with node:8.9.1

```
FROM node:8.9.1
# Java Version
ENV  JAVA_VERSION=9.0.1 \
     JAVA_BUILD=11  \
     JAVA_HOME=/usr/lib/jvm/current-java

#  Openjdk  http://download.java.net/java/GA/jdk9/9.0.1/binaries/openjdk-9.0.1_linux-x64_bin.tar.gz

RUN  apt-get update -y && apt-get upgrade -y

RUN apt-get install wget tar bash -y

RUN cd /tmp && \
    wget "http://download.java.net/java/GA/jdk9/${JAVA_VERSION}/binaries/openjdk-${JAVA_VERSION}_linux-x64_bin.tar.gz" && \
    tar xzf "openjdk-${JAVA_VERSION}_linux-x64_bin.tar.gz" && \
    mkdir -p /usr/lib/jvm && mv "/tmp/jdk-${JAVA_VERSION}" "/usr/lib/jvm/openjdk-${JAVA_VERSION}"  && \
    ln -s "openjdk-${JAVA_VERSION}" $JAVA_HOME && \
    ln -s $JAVA_HOME/bin/java /usr/bin/java && \
    ln -s $JAVA_HOME/bin/jshell /usr/bin/jshell

RUN rm -rf $JAVA_HOME/*.txt && \
    rm -rf $JAVA_HOME/*.html && \
    rm -rf $JAVA_HOME/man && \
    rm -rf $JAVA_HOME/jmods/jdk.* && \
    rm -rf $JAVA_HOME/include && \
    rm -rf $JAVA_HOME/lib/src.zip && \
    rm -rf /tmp/*
```

I used https://github.com/rayyildiz/docker-java9 heavily so they did all the actual hard work =)
I'm no java expert so I'm not sure if any of this is best practice.
