### ISSUE TITLE
Don't require NPM, let users also use Yarn

### ISSUE THREAD

**Issue by oskarkrawczyk** [vuejs-templates/webpack#656]
Currently when using `yarn`:

```
→ yarn run dev
yarn run v0.19.1
$ node build/dev-server.js
module.js:472
    throw err;
    ^

Error: Cannot find module 'npmlog'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:19:13
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:75:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
child_process.js:533
    throw err;
    ^

Error: Command failed: npm --version
module.js:472
    throw err;
    ^

Error: Cannot find module 'npmlog'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:19:13
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:75:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)

    at checkExecSyncError (child_process.js:490:13)
    at Object.execSync (child_process.js:530:13)
    at exec (/Users/oskarkrawczyk/Sites/headway/build/check-versions.js:6:35)
    at Object.<anonymous> (/Users/oskarkrawczyk/Sites/headway/build/check-versions.js:17:21)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by shailendher** [comment]
I tried 'yarn run dev' and it actually works. Perhaps the issue is somewhere else?

**Comment by oskarkrawczyk** [comment]
@shailendher do you have `npm` installed? I don't, which means that it still potentially requires `npm` to be installed on your OS.

**Comment by shailendher** [comment]
Ah! Excuse me. Now I see that in 'check_versions.js' they have an explicit check for it.

**Comment by Aladdin-ADD** [comment]
To get out of the problem, I just created a PR.( #660 )

**Comment by LinusBorg** [comment]
Fixed, thanks for the PR
