### ISSUE TITLE
Production mode

### ISSUE THREAD

**Issue by victorhazbun** [vuejs-templates/webpack#816]
When deploying to production setting `NODE_ENV=production` I get `Cannot GET /`

This only happens on production mode, why?

LOGS:

 ```
ERROR  Failed to compile with 2 errors                                                                                                             01:35:53

 error  in ./src/App.vue

Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
    at Object.module.exports.pitch (/Users/victor/projects/cryptolancer-io/code/frontend-cryptolancer-io/node_modules/extract-text-webpack-plugin/loader.js:25:9)

 @ ./src/App.vue 2:2-371
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/components/Hello.vue

Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
    at Object.module.exports.pitch (/Users/victor/projects/cryptolancer-io/code/frontend-cryptolancer-io/node_modules/extract-text-webpack-plugin/loader.js:25:9)

 @ ./src/components/Hello.vue 2:2-381
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js
```

**Comment by yoyo837** [comment]
'npm run build' will generate 'dist' directory, copy the directory directly to the server.

Can you provide more something about this issue?

**Comment by LinusBorg** [comment]
@victorhazbun Is this still relevant?

**Comment by mymtw** [comment]
this is still actual
```
 ERROR  Failed to compile with 1 errors                                                                                                                                   02:07:32

 error  in ./src/components/HelloWorld.vue

Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
    at Object.pitch (/Users/apple/Developer/vueexample/my-project/node_modules/extract-text-webpack-plugin/dist/loader.js:57:11)

 @ ./src/components/HelloWorld.vue 2:2-373
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js
```

**Comment by LinusBorg** [comment]
Well, you set NODE_ENV to production, but still run the development webpack condig. 

Switching the production config won't work perfectly as well, as the Dr server config is in dev. Maybe we can move that to base.

**Comment by mymtw** [comment]
I changed my scripts, for production, now I'm running it with command `start`:
```
  "scripts": {
    "dev": "webpack-dev-server --inline --progress --config build/webpack.dev.conf.js",
    "start": "node server.js",
    "lint": "eslint --ext .js,.vue src",
    "build": "node build/build.js --prod"
  },
```
and in `server.js`:
```
app.use(express.static(__dirname + '/dist'))

// handle every other route with index.html, which will contain
// a script tag to your application's JavaScript file(s).
app.get('*', function (req, res) {
  res.sendFile(path.resolve(__dirname, 'dist', 'index.html'))
})
```
But maybe it will be better to have any production ready setup in this vuejs-template?

**Comment by LinusBorg** [comment]
Oh, I usually use [http-server](https://www.npmjs.com/package/http-server) when I want to quickly serve the built files locally.
