### ISSUE TITLE
Import JSON does not work with the current webpack configuration

### ISSUE THREAD

**Issue by nijikokun** [vuejs-templates/webpack#835]
```
There was an error while starting the test runner:

/root/projects/test/test/e2e/specs/test.js:1
(function (exports, require, module, __filename, __dirname) { import _JSON$stringify from 'babel-runtime/core-js/json/stringify';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
```

Using the following inside an end to end test will break the test suite:

```
JSON.stringify({})
```

**Comment by nijikokun** [comment]
It appears that the `e2e` tests are missing `BABEL_ENV=test` or a transformation plugin.

**Comment by LinusBorg** [comment]
The webpack config should transpile no matter which env you've set (or not set)

**Comment by dahrens** [comment]
Feels ugly but works for me:

`var JSON = require('babel-runtime/core-js/json/stringify')`

**Comment by 4eek** [comment]
Adding **BABEL_ENV=test** to the e2e task of package.json as follows worked for me...

package.json
```
    ...
    "unit": "cross-env BABEL_ENV=test karma start test/unit/karma.conf.js --single-run",
    "e2e": "BABEL_ENV=test node test/e2e/runner.js",
    ...
```

**Comment by dahrens** [comment]
I digged a little deeper and found that `BABEL_ENV` supports a [fallback](https://babeljs.io/docs/usage/babelrc/#env-option) the points to `NODE_ENV` which seems intended to be used. But in `.babelrc` the configured env is called `test` and the e2e runner.js defines `process.env.NODE_ENV = 'testing'`.
I added the missing env `testing` to **.babelrc**

```javascript
{
  "env":
    "testing": {
      "presets": ["env", "stage-2"]
    }
  }
}
```

Additionally I remove the first line `require('babel-register')` in `nightwatch.conf.js` and now it works as expected.

**Comment by LinusBorg** [comment]
Hey, thanks for digging into this! 

We should definitely fix this in the template. Will get to it when I find time - maybe we can ref actor these `test` / `testing` RMV variables into one.

**Comment by LinusBorg** [comment]
IN #1178 I consolidate the `test` & `testing` env variables into `test`, that should solve this problem.

**Comment by gaastonsr** [comment]
@LinusBorg looking forward to it
