### ISSUE TITLE
Error when running commands

### ISSUE THREAD

**Issue by clementjacquet** [vuejs-templates/webpack#879]
I'm having error while running commands with yarn / npm, all commands fail with this error:

```
clement@clement-X75VC:~/www/chat$ yarn build
yarn build v0.27.5
$ node build/build.js
fs.js:1657
      binding.lstat(baseLong);
              ^

Error: ENOENT: no such file or directory, lstat '/home/clement/www/chat/test'
    at Object.realpathSync (fs.js:1657:15)
    at resolve (/home/clement/www/chat/build/webpack.base.conf.js:8:13)
    at Object.<anonymous> (/home/clement/www/chat/build/webpack.base.conf.js:35:35)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
error Command failed with exit code 1.
```

I tried with other templates such as **webpack-simple** and **browserify** and it run without any error...

Any ideas ?

**Comment by lukaisailovic** [comment]
Same issue

**Comment by oguibueno** [comment]
I created a directory "test" in my project and it worked.

Cheers to @lsgoulart

**Comment by lukaisailovic** [comment]
Simple as that bu fixes it...

**Comment by clementjacquet** [comment]
@oguibueno it fixed it, thanks!

**Comment by mark-rodgers** [comment]
Thanks @oguibueno 
Same issue here on macOS Sierra 10.12.4

**Comment by pongoman** [comment]
Same issue, windows 8, node 8.4, latest vue-cli.

The fix with the test dir worked, thanks.

**Comment by LinusBorg** [comment]
Will fix this adap, but might take a couple of hours until I get to a computer
