### ISSUE TITLE
npm run dev & npm run build failing

### ISSUE THREAD

**Issue by mark-rodgers** [vuejs-templates/webpack#881]
Am I doing something wrong here? Can't seem to get vue-cli working

**npm install -g vue-cli**
```
npm WARN deprecated babel-preset-latest@6.24.1: 💥  preset-latest accomplishes the same task as babel-preset-env. 🙏  Please install it with 'npm install babel-preset-env --save-dev'. '{ "presets": ["latest"] }' to '{ "presets": ["env"] }'. For more info, please check the docs: http://babeljs.io/docs/plugins/preset-env 👌. And let us know how you're liking Babel at @babeljs on 🐦
npm WARN deprecated babel-preset-es2017@6.24.1: We're really excited that you're trying to use ES2017 syntax, but instead of making more yearly presets, Babel has a better preset that we recommend you use instead: npm install babel-preset-env --save-dev. Give us a follow @babeljs to get more updates
npm WARN deprecated babel-preset-es2016@6.24.1: We're really excited that you're trying to use ES2016 syntax, but instead of making more yearly presets, Babel has a better preset that we recommend you use instead: npm install babel-preset-env --save-dev. Give us a follow @babeljs to get more updates
/usr/local/bin/vue -> /usr/local/lib/node_modules/vue-cli/bin/vue
/usr/local/bin/vue-init -> /usr/local/lib/node_modules/vue-cli/bin/vue-init
/usr/local/bin/vue-build -> /usr/local/lib/node_modules/vue-cli/bin/vue-build
/usr/local/bin/vue-list -> /usr/local/lib/node_modules/vue-cli/bin/vue-list

> fsevents@1.1.2 install /usr/local/lib/node_modules/vue-cli/node_modules/fsevents
> node install

[fsevents] Success: "/usr/local/lib/node_modules/vue-cli/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
+ vue-cli@2.8.2
added 962 packages in 32.243s
```

**vue init webpack my-project**
```
? Project name my-project
? Project description A Vue.js project
? Author mark-rodgers <11markrodgers11@gmail.com>
? Vue build standalone
? Install vue-router? Yes
? Use ESLint to lint your code? No
? Setup unit tests with Karma + Mocha? No
? Setup e2e tests with Nightwatch? No

   vue-cli · Generated "my-project".

   To get started:

     cd my-project
     npm install
     npm run dev

   Documentation can be found at https://vuejs-templates.github.io/webpack
```

**cd my-project**

**npm install**

```
> fsevents@1.1.2 install /Users/mrodgers/code/web/local/plantool/my-project/node_modules/fsevents
> node install

[fsevents] Success: "/Users/mrodgers/code/web/local/plantool/my-project/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
npm notice created a lockfile as package-lock.json. You should commit this file.
added 918 packages in 30.323s
```

**npm run dev**

```
> my-project@1.0.0 dev /Users/mrodgers/code/web/local/plantool/my-project
> node build/dev-server.js

fs.js:1657
      binding.lstat(baseLong);
              ^

Error: ENOENT: no such file or directory, lstat '/Users/mrodgers/code/web/local/plantool/my-project/test'
    at Object.realpathSync (fs.js:1657:15)
    at resolve (/Users/mrodgers/code/web/local/plantool/my-project/build/webpack.base.conf.js:8:13)

    at Object.<anonymous> (/Users/mrodgers/code/web/local/plantool/my-project/build/webpack.base.conf.js:40:35)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-project@1.0.0 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-project@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mrodgers/.npm/_logs/2017-08-28T21_51_43_425Z-debug.log
```

**Comment by mark-rodgers** [comment]
Whoops, right after posting I found someone else having the same issue #879 . 

Not sure why but found this fix in the comments from the issue mentioned above

> I created a directory "test" in my project and it worked.
>
>Cheers to @lsgoulart

**Comment by shaun-sweet** [comment]
I think this only applied to projects made without testing invoked via the wizard

**Comment by SirM2z** [comment]
Error when dont setup unit tests
```
fs.js:1657
      binding.lstat(baseLong);
              ^

Error: ENOENT: no such file or directory, lstat 'path\to\test'
```
I think is the problem of `fs.realpathSync` with this [commit](https://github.com/vuejs-templates/webpack/commit/7c1e230fa10b466bdeb6e4f48a2786905842830e)

**Comment by mark-rodgers** [comment]
`Error: ENOENT: no such file or directory, lstat '/Users/mrodgers/code/web/local/plantool/my-project/test'`

Wow, can't believe I overlooked that. Definitely need to start getting more sleep 😴 the answer was literally in my question. Thanks again.

Hopefully this gets patched soon. I know I've used Vues in the past without unit testing and never have this problem.

**Comment by LinusBorg** [comment]
Closing as a duplicate
